version: '3.8'

services:
  # frontend:
  #   build: 
  #     context: ./app
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3003:80"  # 假设前端在容器的 80 端口运行
  #   networks:
  #     - app-network

  coshop-gateway:
    build:
      context: ./server/coshop-gateway
      dockerfile: Dockerfile
    ports:
      - "9527:9527"
    networks:
      - app-network

  # coshop-core:
  #   build:
  #     context: ./server/coshop-core
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - app-network

networks:
  app-network:

# db:
# image: mysql:5.7
# restart: always
# ports:
#   - "3306:3306"
# environment:
#   MYSQL_ROOT_PASSWORD: 123456
#   MYSQL_DATABASE: coshop
#   MYSQL_USER: coshop
#   MYSQL_PASSWORD: 123456
# volumes:
#   - ./db:/var/lib/mysql
