version: '3.8'
services:
  frontend:
    image: node:18
    working_dir: /frontend
    volumes:
      - ./app:/frontend
    ports:
      - "3003:3000"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend

  backend:
    image: openjdk:8-jdk
    working_dir: /app
    volumes:
      - ./server:/app
    ports:
      - "5005:5000"
    command: sh -c "mvn clean install && java -jar target/backend-0.0.1-SNAPSHOT.jar"

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    # environment:
    #   MYSQL_ROOT_PASSWORD: mypassword
    #   MYSQL_DATABASE: mydatabase
    #   MYSQL_USER: user
    #   MYSQL_PASSWORD: userpassword
    # volumes:
    #   - db-data:/var/lib/mysql
    # restart: always
