version: '3.8'

services:
  frontend:
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3003:80"  # 假设前端在容器的 80 端口运行

  coshop-gateway:
    build:
      context: ./server/coshop
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # 按需调整端口映射
    depends_on:
      - coshop-api

  coshop-core:
    build:
      context: ./server/coshop
      dockerfile: Dockerfile
    ports:
      - "8081:8081" # 按需调整端口映射
    depends_on:
      - coshop-api

  coshop-api:
    build:
      context: ./server/coshop
      dockerfile: Dockerfile
